// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Program;

#nullable disable

namespace S00238688_ClassLibrary.Migrations
{
    [DbContext(typeof(ConsoleEcommerceContext))]
    partial class ConsoleEcommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("S00238688_ClassLibrary.CategoryClass", b =>
                {
                    b.Property<int>("Category_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_ID = 1,
                            Name = "Trading Cards"
                        },
                        new
                        {
                            Category_ID = 2,
                            Name = "Action Figures"
                        });
                });

            modelBuilder.Entity("S00238688_ClassLibrary.CollectibleClass", b =>
                {
                    b.Property<int>("Collectible_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Collectible_ID"));

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock_Quantity")
                        .HasColumnType("int");

                    b.HasKey("Collectible_ID");

                    b.ToTable("Collectibles");

                    b.HasData(
                        new
                        {
                            Collectible_ID = 1,
                            Category_ID = 1,
                            Condition = "Mint",
                            Name = "Pikachu Holo Card",
                            Price = 120.00m,
                            Stock_Quantity = 5
                        },
                        new
                        {
                            Collectible_ID = 2,
                            Category_ID = 2,
                            Condition = "Good",
                            Name = "Batman Figure",
                            Price = 80.00m,
                            Stock_Quantity = 3
                        },
                        new
                        {
                            Collectible_ID = 3,
                            Category_ID = 2,
                            Condition = "Near Mint",
                            Name = "Yoda Figure",
                            Price = 95.50m,
                            Stock_Quantity = 2
                        });
                });

            modelBuilder.Entity("S00238688_ClassLibrary.OrderClass", b =>
                {
                    b.Property<int>("Order_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_ID"));

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Order_ID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Order_ID = 101,
                            Order_Status = "Shipped",
                            Payment_Status = "Paid",
                            Total_Price = 120.00m,
                            User_ID = 1
                        },
                        new
                        {
                            Order_ID = 102,
                            Order_Status = "Processing",
                            Payment_Status = "Pending",
                            Total_Price = 175.50m,
                            User_ID = 2
                        });
                });

            modelBuilder.Entity("S00238688_ClassLibrary.OrderItemClass", b =>
                {
                    b.Property<int>("Order_Item_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_Item_ID"));

                    b.Property<int>("Collectible_ID")
                        .HasColumnType("int");

                    b.Property<int>("Order_ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Unit_Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Order_Item_ID");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Order_Item_ID = 1,
                            Collectible_ID = 1,
                            Order_ID = 101,
                            Quantity = 1,
                            Unit_Price = 120.00m
                        },
                        new
                        {
                            Order_Item_ID = 2,
                            Collectible_ID = 2,
                            Order_ID = 102,
                            Quantity = 1,
                            Unit_Price = 80.00m
                        },
                        new
                        {
                            Order_Item_ID = 3,
                            Collectible_ID = 3,
                            Order_ID = 103,
                            Quantity = 1,
                            Unit_Price = 95.50m
                        });
                });

            modelBuilder.Entity("S00238688_ClassLibrary.UserClass", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_ID = 1,
                            Email = "alice@example.com",
                            Name = "Alice Carter",
                            Role = "customer"
                        },
                        new
                        {
                            User_ID = 2,
                            Email = "bob@example.com",
                            Name = "Bob Nguyen",
                            Role = "customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
